server:
  port: 9000

spring:
  application:
    name: demo
  profiles:
    include: oauth

  datasource:
    platform: mysql
    url: jdbc:mysql://kayden.ccetd3jlv36v.ap-northeast-2.rds.amazonaws.com/dev?autoReconnect=true # 변경해주세요
    username: admin # 변경해주세요
    password: jinbeom512 # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전 